version = 1

test_patterns = [
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/__tests__/*.ts",
  "**/__tests__/*.tsx",
  "cypress/**/*.cy.ts"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "cypress"
  ]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile",
    "Dockerfile.test"
  ]