name: tasktix

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@mariadb/${DB_DATABASE}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - ENABLE_PASSWORD_STRENGTH_CHECK=true
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
