name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build web image metadata
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tasktix/tasktix-web
          labels: |
            org.opencontainers.image.source=https://github.com/Tasktix/Tasktix
            org.opencontainers.image.description=A powerful and flexible task-tracking tool for all.
            org.opencontainers.image.licenses=AGPL-3.0-or-later
          tags: |
            latest
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta-web.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}

  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build deploy image metadata
        id: meta-deploy
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tasktix/tasktix-deploy
          annotations: |
            org.opencontainers.image.description=A powerful and flexible task-tracking tool for all.
            org.opencontainers.image.licenses=AGPL-3.0-or-later
          tags: |
            latest
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
      - name: Build and push deploy image
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta-deploy.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-deploy.outputs.tags }}
          file: Dockerfile.deploy
